<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-04T16:39:32 IST" name="Suite" finished-at="2022-01-04T16:39:34 IST" duration-ms="2116">
    <groups>
    </groups>
    <test started-at="2022-01-04T16:39:32 IST" name="Test" finished-at="2022-01-04T16:39:34 IST" duration-ms="2116">
      <class name="testclasses.LoginTest">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:testclasses.LoginTest@13b13b5d]" started-at="2022-01-04T16:39:29 IST" name="initDriver" finished-at="2022-01-04T16:39:32 IST" duration-ms="3111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method is-config="true" signature="createObject()[pri:0, instance:testclasses.LoginTest@13b13b5d]" started-at="2022-01-04T16:39:32 IST" name="createObject" finished-at="2022-01-04T16:39:32 IST" duration-ms="28" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createObject -->
        <test-method signature="loginToApp()[pri:1, instance:testclasses.LoginTest@13b13b5d]" started-at="2022-01-04T16:39:32 IST" name="loginToApp" finished-at="2022-01-04T16:39:32 IST" duration-ms="367" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="validatePage()[pri:2, instance:testclasses.LoginTest@13b13b5d]" started-at="2022-01-04T16:39:32 IST" name="validatePage" finished-at="2022-01-04T16:39:33 IST" duration-ms="776" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at testclasses.LoginTest.validatePage(LoginTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testclasses.LoginTest@13b13b5d]" started-at="2022-01-04T16:39:34 IST" name="tearDown" finished-at="2022-01-04T16:39:34 IST" duration-ms="220" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testclasses.LoginTest -->
      <class name="testclasses.DashBoardTest">
        <test-method is-config="true" signature="createObject()[pri:0, instance:testclasses.DashBoardTest@1649b0e6]" started-at="2022-01-04T16:39:33 IST" name="createObject" finished-at="2022-01-04T16:39:33 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createObject -->
        <test-method signature="selectShare()[pri:3, instance:testclasses.DashBoardTest@1649b0e6]" started-at="2022-01-04T16:39:33 IST" name="selectShare" finished-at="2022-01-04T16:39:33 IST" duration-ms="436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectShare -->
        <test-method signature="buyShares()[pri:4, instance:testclasses.DashBoardTest@1649b0e6]" started-at="2022-01-04T16:39:33 IST" name="buyShares" finished-at="2022-01-04T16:39:34 IST" duration-ms="302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buyShares -->
      </class> <!-- testclasses.DashBoardTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
